-- 由 booklist.json 自动生成，请勿手改（改后重跑 node generate-seed.cjs）
-- 幂等：先清空再插入，保证与 booklist.json 一致
DELETE FROM books;

INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (1, '酒店英语与国际服务文化 上册（移动学习版）101', '', 'covers/image1.jpg', 9.9, 17, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (2, '酒店英语与国际服务文化 下册（移动学习版）', '', 'covers/image2.jpg', 9.9, 16, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (3, '新视野大学英语 2 视听说教程（第三版 思政智慧版）', '', 'covers/image3.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (4, '新视野大学英语 3 视听说教程（第三版 思政智慧版）', '', 'covers/image4.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (5, '朗文旅游英语 初级・学生用书', '', 'covers/image5.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (6, '高职国际英语 进阶综合教程 2 学生用书', '', 'covers/image6.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (7, '高职国际英语 进阶综合教程 3 学生用书', '', 'covers/image7.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (8, '实用阶梯英语 阅读教程（旅游篇 Ⅰ）', '', 'covers/image8.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (9, '新视野大学英语 1 视听说教程（第三版 新思政智慧版）', '', 'covers/image9.jpg', 9.9, 18, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (10, '职场实用英语交际教程（初级）', '', 'covers/image10.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (11, '高职国际英语 进阶综合教程 3 学生用书', '', 'covers/image11.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (12, '高职国际进阶英语 综合教程 3 学生用书', '', 'covers/image12.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (13, '新媒体技术基础初级', '', 'covers/image13.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (14, '新媒体技术基础中级', '', 'covers/image14.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (15, '英语泛读教程1', '', 'covers/image15.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (16, '0-3婴幼儿音乐启蒙教育', '', 'covers/image16.jpg', 9.9, 13, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (17, '市场调查与分析（第二版）', '', 'covers/image17.jpg', 9.9, 18, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (18, '领队英语（第 5 版）', '', 'covers/image18.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (19, '市场调查与数据分析', '', 'covers/image19.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (20, '旅游英语视听说（第二版）', '', 'covers/image20.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (21, '英语泛读 1（微课版）', '', 'covers/image21.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (22, '实用阶梯英语 翻译教程（第四版）', '', 'covers/image22.jpg', 9.9, 16, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (23, '领队英语（第 6 版）', '', 'covers/image23.jpg', 9.9, 13, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (24, '朗文旅游英语 初级・学生用书', '', 'covers/image24.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (25, '食品营养与健康', '', 'covers/image25.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (26, '英语翻译与导游英语（英汉互译 口译笔译）', '', 'covers/image26.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (27, '会展英语（第 2 版）', '', 'covers/image27.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (28, '国际邮轮服务英语', '', 'covers/image28.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (29, '新职业英语 行业篇 旅游英语 2（第三版）', '', 'covers/image29.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (30, '新职业英语 行业篇 旅游英语 1（第三版）', '', 'covers/image30.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (31, '母婴护理', '', 'covers/image31.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (32, '幼儿运动组织与指导', '', 'covers/image32.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (33, '婴幼儿伤害预防与处理', '', 'covers/image33.jpg', 9.9, 16, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (34, '餐饮服务与管理', '', 'covers/image34.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (35, '婴幼儿家园共育（微课版）', '', 'covers/image35.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (36, '婴幼儿发展引导', '', 'covers/image36.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (37, '婴幼儿心理发展', '', 'covers/image37.jpg', 9.9, 15, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (38, '婴幼儿生理基础', '', 'covers/image38.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (39, 'AIGC 与新媒体运营技能实战', '', 'covers/image39.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (40, '统计学基础及应用', '', 'covers/image40.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (41, '旅游概论第四版', '', 'covers/image41.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (42, '婴幼儿行为观察与指导', '', 'covers/image42.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (43, '酒店 OTA 平台运营增长指南', '', 'covers/image43.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (44, '酒店数字化运营概论', '', 'covers/image44.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (45, '旅游服务礼仪', '', 'covers/image45.jpg', 9.9, 17, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (46, '幼儿照护职业技能教材（基础知识）', '', 'covers/image46.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (47, '情绪管理', '', 'covers/image47.jpg', 9.9, 18, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (48, '幼儿照护职业技能教材（中级）', '', 'covers/image48.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (49, '酒店英语', '', 'covers/image49.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (50, '前厅服务与数字化运营', '', 'covers/image50.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (51, '现代市场营销（第三版）', '', 'covers/image51.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (52, '商业文化与素养（第二版）', '', 'covers/image52.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (53, '消费心理学（第二版）', '', 'covers/image53.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (54, '酒店人力资源管理', '', 'covers/image54.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (55, '侍酒服务与管理', '', 'covers/image55.jpg', 9.9, 13, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (56, '新媒体文案策划与写作 从入门到精通 微课版', '', 'covers/image56.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (57, '市场调查与分析（第二版）', '', 'covers/image57.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (58, '0‑3 岁婴幼儿艺术启蒙教育（融媒体版）', '', 'covers/image58.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (59, '服务心理学（第四版）', '', 'covers/image59.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (60, '葡萄酒文化与风土', '', 'covers/image60.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (61, '旅游应用文写作（第二版）', '', 'covers/image61.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (62, '人体工程学', '', 'covers/image62.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (63, '人体工程学', '', 'covers/image63.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (64, '政策与法律法规（第八版）', '', 'covers/image64.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (65, '葡萄酒历史与风土', '', 'covers/image65.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (66, '地方导游基础知识（第七版）', '', 'covers/image66.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (67, '新媒体营销（第三版）', '', 'covers/image67.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (68, '导游业务（第七版）', '', 'covers/image68.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (69, '导游业务（第九版）', '', 'covers/image69.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (70, '地方导游基础知识（第八版）', '', 'covers/image70.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (71, '全国导游基础知识（第七版）', '', 'covers/image71.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (72, '地方导游基础知识（第六版）', '', 'covers/image72.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (73, '政策与法律法规（第七版）', '', 'covers/image73.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (74, '休闲学概论（第四版）', '', 'covers/image74.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (75, '地方导游基础知识（第8版）', '', 'covers/image75.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (76, '导游业务（第八版）', '', 'covers/image76.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (77, '政策与法律法规（第九版）', '', 'covers/image77.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (78, '全国导游基础知识（第九版）', '', 'covers/image78.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (79, '全国导游基础知识（第八版）', '', 'covers/image79.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (80, '世界儿歌钢琴公式化即兴伴奏', '', 'covers/image80.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (81, '旅游市场营销与策划——理论、实务、案例、实训（第四版）', '', 'covers/image81.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (82, '会计基础', '', 'covers/image82.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (83, '新媒体运营（微课版）', '', 'covers/image83.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (84, '茶艺（第四版）', '', 'covers/image84.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (85, '0—3岁婴幼儿营养与喂养', '', 'covers/image85.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (86, '旅游市场营销与策划——理论、实务、案例、实训（第五版）', '', 'covers/image86.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (87, '市场营销基础与实务 微课版 第2版', '', 'covers/image87.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (88, '旅游心理学', '', 'covers/image88.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (89, '旅游学概论（第二版）', '', 'covers/image89.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (90, '旅游消费者行为（第三版）', '', 'covers/image90.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (91, '舞蹈基础（第二版）', '', 'covers/image91.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (92, '托育机构环境创设', '', 'covers/image92.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (93, '旅游学概论', '', 'covers/image93.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (94, '旅游心理学（第8版）', '', 'covers/image94.jpg', 9.9, 14, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (95, '幼儿游戏活动指导', '', 'covers/image95.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (96, '0~6岁儿童心理行为发展评估', '', 'covers/image96.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (97, '旅游消费者行为（第二版）', '', 'covers/image97.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (98, '管理学基础与实务', '', 'covers/image98.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (99, '管理学基础（第五版）', '', 'covers/image99.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (100, '现代礼仪训练', '', 'covers/image100.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (101, '酒水服务 第2版', '', 'covers/image101.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (102, '酒店与餐饮', '', 'covers/image102.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (103, '智慧旅游运营实务', '', 'covers/image103.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (104, '项目管理 第2版', '', 'covers/image104.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (105, '广东旅游资源概论', '', 'covers/image105.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (106, '项目管理', '', 'covers/image106.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (107, '茶文化与茶艺 第3版', '', 'covers/image107.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (108, '新媒体营销 微课版 第2版', '', 'covers/image108.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (109, '基础会计 附微课视频', '', 'covers/image109.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (110, '研学旅行指导师实务 第2版', '', 'covers/image110.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (111, '口才语演讲训练教程第二版', '', 'covers/image111.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (112, 'Excel在财务中的应用 第二版', '', 'covers/image112.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (113, '中国文化概况 修订版', '', 'covers/image113.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (114, '经济学基础 第2版', '', 'covers/image114.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (115, '会展设计 活页式', '', 'covers/image115.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (116, '咖啡制作', '', 'covers/image116.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (117, '会展概论 第四版', '', 'covers/image117.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (118, '酒店管理概论 第2版', '', 'covers/image118.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (119, '经济法基础考点汇编 2025年度', '', 'covers/image119.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (120, '基础会计 微课版 第4版', '', 'covers/image120.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (121, '初级会计实务考点汇编 2025年度', '', 'covers/image121.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (122, '市场调查与分析 第三版', '', 'covers/image122.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (123, '管理学 第五版', '', 'covers/image123.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (124, '初级会计实务 2025年度', '', 'covers/image124.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (125, '商务礼仪实务 第4版', '', 'covers/image125.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (126, '幼儿教师必知礼仪规范与易错细节', '', 'covers/image126.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (127, '商务数据分析与应用（第二版）', '', 'covers/image127.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (128, '中医儿科学（第5版）', '', 'covers/image128.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (129, '形势与政策指导2021年高职高专版', '', 'covers/image129.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (130, '口才与演讲训练教程（第三版）', '', 'covers/image130.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (131, '管理学基础与实务（第3版）', '', 'covers/image131.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (132, '资料员岗位知识与专业技能（第三版）', '', 'covers/image132.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (133, '会展营销', '', 'covers/image133.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (134, 'Photoshop建筑与室内效果图后期制作（第2版）', '', 'covers/image134.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (135, '建筑CAD教程', '', 'covers/image135.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (136, 'AutoCAD建筑绘图教程', '', 'covers/image136.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (137, '园林植物景观规划设计', '', 'covers/image137.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (138, '建筑设计方法', '', 'covers/image138.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (139, 'AutoCAD施工图绘制（第三版）', '', 'covers/image139.jpg', 9.9, 40, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (140, 'AutoCAD施工图绘制（第二版）', '', 'covers/image140.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (141, '场地设计（第二版）', '', 'covers/image141.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (142, '室内设计基础', '', 'covers/image142.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (143, '幼儿园建筑设计（第二版）', '', 'covers/image143.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (144, 'BIM建模与应用教程', '', 'covers/image144.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (145, 'Java语言程序设计（一）2017年版', '', 'covers/image145.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (146, 'UG NX12.0注塑模具设计实例教程修订版', '', 'covers/image146.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (147, 'UG NX12完全实训手册', '', 'covers/image147.jpg', 9.9, 14, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (148, '消防设施操作员（基础知识）', '', 'covers/image148.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (149, '消防设施操作员（中级）', '', 'covers/image149.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (150, '混凝土结构施工图平面整体表示方法制图规则和构造详图（独立基础、条形基础、筏形基础、桩基础）22G101‑3', '', 'covers/image150.jpg', 9.9, 22, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (151, '混凝土结构施工图平面整体表示方法制图规则和构造详图（现浇混凝土框架、剪力墙、梁、板）22G101‑1', '', 'covers/image151.jpg', 9.9, 17, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (152, '混凝土结构施工图平面整体表示方法制图规则和构造详图（现浇混凝土板式楼梯）22G101‑2', '', 'covers/image152.jpg', 9.9, 16, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (153, 'SolidWorks三维机械设计实训教程', '', 'covers/image153.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (154, '无线局域网组建与优化 HCIA‑WLAN 微课版', '', 'covers/image154.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (155, '工业控制网络', '', 'covers/image155.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (156, '电路与电工技术 第二版', '', 'covers/image156.jpg', 9.9, 0, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (157, 'EPLAN电气设计', '', 'covers/image157.jpg', 9.9, 18, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (158, 'PLC应用与实践（三菱）', '', 'covers/image158.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (159, '网络营销推广与策划 第3版 慕课版', '', 'covers/image159.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (160, 'SolidWorks三维建模项目教程', '', 'covers/image160.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (161, '工业控制网络 第2版 微课版', '', 'covers/image161.jpg', 9.9, 26, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (162, '汽车构造与原理201', '', 'covers/image162.jpg', 9.9, 26, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (163, '电梯维修与保养', '', 'covers/image163.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (164, '电梯结构及原理', '', 'covers/image164.jpg', 9.9, 31, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (165, '电梯营销', '', 'covers/image165.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (166, '数字电子技术项目教程 第2版', '', 'covers/image166.jpg', 9.9, 18, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (167, '电梯安全技术', '', 'covers/image167.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (168, '汽车营销', '', 'covers/image168.jpg', 9.9, 26, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (169, 'ABB工业机器人虚拟仿真与离线编程', '', 'covers/image169.jpg', 9.9, 17, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (170, '智能小车系统设计——基于STM32', '', 'covers/image170.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (171, '模具设计基础 第3版', '', 'covers/image171.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (172, '嵌入式系统开发基础教程——基于STM32F103系列', '', 'covers/image172.jpg', 9.9, 26, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (173, '可编程控制器技术 第二版', '', 'covers/image173.jpg', 9.9, 30, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (174, '传感器应用技术', '', 'covers/image174.jpg', 9.9, 19, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (175, '电子产品设计案例教程（微课版）基于嘉立创EDA（专业版）', '', 'covers/image175.jpg', 9.9, 15, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (176, '控制系统应用——基于罗克韦尔PLC、变频器及触摸屏', '', 'covers/image176.jpg', 9.9, 38, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (177, '零部件测绘实训指导 第四版', '', 'covers/image177.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (178, '汽车售后服务与管理', '', 'covers/image178.jpg', 9.9, 16, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (179, '汽油发动机电控系统检修 第2版', '', 'covers/image179.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (180, '零部件测绘实训指导 第三版', '', 'covers/image180.jpg', 9.9, 19, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (181, 'PLM技术及应用', '', 'covers/image181.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (182, '电机与电气控制技术项目式教程第2版', '', 'covers/image182.jpg', 9.9, 13, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (183, 'STC单片机应用技术——从设计、仿真到实践 第2版', '', 'covers/image183.jpg', 9.9, 15, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (184, '机械制造基础 第3版', '', 'covers/image184.jpg', 9.9, 24, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (185, 'STC单片机应用技术—从设计、仿真到实践第2版', '', 'covers/image185.jpg', 9.9, 27, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (186, 'CAPP数字化工艺设计', '', 'covers/image186.jpg', 9.9, 22, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (187, '机电产品营销 第2版', '', 'covers/image187.jpg', 9.9, 28, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (188, '新能源汽车专业英语', '', 'covers/image188.jpg', 9.9, 20, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (189, '机器视觉', '', 'covers/image189.jpg', 9.9, 14, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (190, '电梯自动控制技术 第2版', '', 'covers/image190.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (191, '机械制造工艺与机床夹具 第4版', '', 'covers/image191.jpg', 9.9, 23, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (192, '机械制造工艺与机床夹具 第3版', '', 'covers/image192.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (193, '传感器原理与应用', '', 'covers/image193.jpg', 9.9, 18, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (194, '数控机床结构与维护 第2版', '', 'covers/image194.jpg', 9.9, 30, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (195, '传感器与检测技术 第3版', '', 'covers/image195.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (196, '机械零件三维设计（SolidWorks）', '', 'covers/image196.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (197, '人工智能应用导论', '', 'covers/image197.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (198, '机械设计基础', '', 'covers/image198.jpg', 9.9, 41, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (199, '网页设计与制作', '', 'covers/image199.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (200, '汽车传感器技术', '', 'covers/image200.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (201, 'Vue.js前端开发实战 第2版', '', 'covers/image201.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (202, '电机与拖动 第4版 附微课视频', '', 'covers/image202.jpg', 9.9, 30, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (203, '新能源汽车电气系统检修', '', 'covers/image203.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (204, 'Linux系统管理及应用项目式教程 RHEL 7.4/CentOS 7.4 微课版', '', 'covers/image204.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (205, 'Vue.js开发教程', '', 'covers/image205.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (206, '新能源汽车电力电子技术', '', 'covers/image206.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (207, 'Python语言程序设计实训教程', '', 'covers/image207.jpg', 9.9, 59, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (208, '单片机原理实验指导与课程设计', '', 'covers/image208.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (209, '纯电动汽车构造与检修', '', 'covers/image209.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (210, '新能源汽车概论第2版', '', 'covers/image210.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (211, '混合动力汽车构造与维修第二版', '', 'covers/image211.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (212, '模拟电子技术应用 微课版', '', 'covers/image212.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (213, '电子技术基础 第5版 微课版', '', 'covers/image213.jpg', 9.9, 80, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (214, '电工基础 第4版 微课版', '', 'covers/image214.jpg', 9.9, 28, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (215, '机械产品零部件三维建模实用教程 UG NX 12.0版', '', 'covers/image215.jpg', 9.9, 15, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (216, '电子技术 第4版 附微课视频 附带活页式实训手册', '', 'covers/image216.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (217, '电工电子技术 第5版 微课版', '', 'covers/image217.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (218, '模拟电子技术微课版', '', 'covers/image218.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (219, '电工技术基础 第4版 微课版', '', 'covers/image219.jpg', 9.9, 114, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (220, '电子技术基础 第4版 微课版', '', 'covers/image220.jpg', 9.9, 52, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (221, 'C 语言程序设计项目化教程', '', 'covers/image221.jpg', 9.9, 78, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (222, 'ABB 工业机器人虚拟仿真技术 —— 基于工业机器人应用编程 1+X 证书考核平台', '', 'covers/image222.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (223, '工业机器人应用编程（FANUC）中级', '', 'covers/image223.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (224, '工业机器人应用编程(ABB)中级', '', 'covers/image224.jpg', 9.9, 29, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (225, '电工技术 第5版', '', 'covers/image225.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (226, '数字电子技术 第6版', '', 'covers/image226.jpg', 9.9, 25, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (227, '数控加工程序编制及操作 第3版', '', 'covers/image227.jpg', 9.9, 62, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (228, '机械设计基础 第2版', '', 'covers/image228.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (229, '机械识图与公差配合', '', 'covers/image229.jpg', 9.9, 35, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (230, '机械工程材料', '', 'covers/image230.jpg', 9.9, 56, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (231, '汽车机械基础', '', 'covers/image231.jpg', 9.9, 18, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (232, '汽车营销', '', 'covers/image232.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (233, 'SolidWorks中文版基础教程2022', '', 'covers/image233.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (234, 'ABB工业机器人编程与操作', '', 'covers/image234.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (235, '新能源汽车电力电子技术', '', 'covers/image235.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (236, '物联网设备安装与调试', '', 'covers/image236.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (237, '计算机应用基础案例教程微课版', '', 'covers/image237.jpg', 9.9, 16, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (238, '汽车营销第3版', '', 'covers/image238.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (239, 'GNU/Linux编程第2版微课版', '', 'covers/image239.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (240, '机械制造工艺与机床夹具第3版', '', 'covers/image240.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (241, 'C语言程序设计任务驱动式教程 第2版 微课版', '', 'covers/image241.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (242, 'ROS机器人编程零基础入门与实践', '', 'covers/image242.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (243, '数字电子技术基础 第六版', '', 'covers/image243.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (244, '电梯检测技术', '', 'covers/image244.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (245, '机械设计基础 第二版', '', 'covers/image245.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (246, '机械设计基础 第五版', '', 'covers/image246.jpg', 9.9, 72, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (247, '机械基础 第五版', '', 'covers/image247.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (248, '机械设计基础课程设计指导书 第五版', '', 'covers/image248.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (249, '逆向工程与3D打印技术', '', 'covers/image249.jpg', 9.9, 94, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (250, '机械制图 第六版', '', 'covers/image250.jpg', 9.9, 72, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (251, 'MCGS嵌入板组态应用技术第2版', '', 'covers/image251.jpg', 9.9, 52, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (252, '工业机器人技术基础', '', 'covers/image252.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (253, '工业机器人工作站系统集成（ABB）', '', 'covers/image253.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (254, '工业机器人技术基础 第2版', '', 'covers/image254.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (255, '工业机器人离线编程（ABB）第2版', '', 'covers/image255.jpg', 9.9, 22, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (256, '工业机器人离线编程（FANUC）', '', 'covers/image256.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (257, '工业机器人离线编程（ABB）', '', 'covers/image257.jpg', 9.9, 22, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (258, '单片机应用技术（C语言版）第4版', '', 'covers/image258.jpg', 9.9, 35, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (259, '单片机应用技术（经典项目化案例式新形态活页教材）第5版复印版没活页', '', 'covers/image259.jpg', 9.9, 41, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (260, '单片机应用技术（经典项目化案例式新形态活页教材）第5版', '', 'covers/image260.jpg', 9.9, 13, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (261, '短视频编辑与制作（全彩版）', '', 'covers/image261.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (262, '短视频策划、拍摄、制作与运营', '', 'covers/image262.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (263, '微信小程序开发实战第2版', '', 'covers/image263.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (264, '智能网联汽车概论', '', 'covers/image264.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (265, '建设工程造价控制与管理第三版', '', 'covers/image265.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (266, '机械零件测绘（第二版）', '', 'covers/image266.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (267, '公差配合与机械测量第二版', '', 'covers/image267.jpg', 9.9, 50, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (268, '公差配合与技术测量第2版', '', 'covers/image268.jpg', 9.9, 24, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (269, '液压与气动技术（第二版）', '', 'covers/image269.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (270, '公差配合与技术测量（含微课）', '', 'covers/image270.jpg', 9.9, 20, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (271, '中国建筑史（第七版）', '', 'covers/image271.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (272, '建筑工程招投标与合同管理', '', 'covers/image272.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (273, '安装工程计量与计价', '', 'covers/image273.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (274, '建筑结构选型（第二版）', '', 'covers/image274.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (275, '住宅建筑设计原理（第四版）', '', 'covers/image275.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (276, '工程招投标与合同管理', '', 'covers/image276.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (277, '居住区规划设计（第二版）', '', 'covers/image277.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (278, '工程经济', '', 'covers/image278.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (279, '外国近现代建筑史（第二版）', '', 'covers/image279.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (280, '建筑装饰工程施工', '', 'covers/image280.jpg', 9.9, 14, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (281, '外国建筑史（19世纪末叶以前）（第四版）', '', 'covers/image281.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (282, '市政工程计量与计价（第五版）（市政工程技术专业适用）', '', 'covers/image282.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (283, 'BIM应用教程：Revit Architecture2016（第二版）', '', 'covers/image283.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (284, '地基与基础工程', '', 'covers/image284.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (285, 'BIM建筑建模', '', 'covers/image285.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (286, '市政管道工程施工（第五版）（市政工程技术专业适用）', '', 'covers/image286.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (287, '结构工程BIM技术应用', '', 'covers/image287.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (288, '建筑施工组织与管理（第3版）（微课版）', '', 'covers/image288.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (289, '结构工程BIM技术应用第二版', '', 'covers/image289.jpg', 9.9, 22, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (290, '环境生态学（第三版）', '', 'covers/image290.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (291, '环境管理（第四版）', '', 'covers/image291.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (292, '固体废物处理处置', '', 'covers/image292.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (293, '土木工程制图习题集', '', 'covers/image293.jpg', 9.9, 17, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (294, '土木工程制图（含习题集）', '', 'covers/image294.jpg', 9.9, 20, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (295, '建设工程法规', '', 'covers/image295.jpg', 9.9, 19, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (296, '建筑构造（下册）（第六版）', '', 'covers/image296.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (297, '建筑构造（上册）（第六版）', '', 'covers/image297.jpg', 9.9, 19, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (298, '大气污染治理技术', '', 'covers/image298.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (299, '环境微生物（第四版）', '', 'covers/image299.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (300, '环境监测', '', 'covers/image300.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (301, '建筑构造 第三版', '', 'covers/image301.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (302, '安装工程计量与计价 第五版', '', 'covers/image302.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (303, '建筑工程测量（含实验指导手册）第三版', '', 'covers/image303.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (304, '建设工程法规 第四版', '', 'covers/image304.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (305, '建筑工程测量 第四版', '', 'covers/image305.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (306, '建筑设备识图与施工工艺 第三版', '', 'covers/image306.jpg', 9.9, 20, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (307, '建筑施工技术 第四版', '', 'covers/image307.jpg', 9.9, 0, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (308, '建筑工程施工技术  第四版', '', 'covers/image308.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (309, '建筑工程造价控制与管理  第三版', '', 'covers/image309.jpg', 9.9, 16, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (310, '钢筋平法识图与计算 第3版', '', 'covers/image310.jpg', 9.9, 22, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (311, '钢筋平法识图与计算 第2版', '', 'covers/image311.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (312, '土力学与地基基础 第3版', '', 'covers/image312.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (313, '土力学与地基基础 第4版', '', 'covers/image313.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (314, '房屋构成与构造 第二版', '', 'covers/image314.jpg', 9.9, 22, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (315, '建筑工程制图 第二版', '', 'covers/image315.jpg', 9.9, 66, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (316, '工程项目招投标与合同管理', '', 'covers/image316.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (317, '装配式混凝土建筑施工', '', 'covers/image317.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (318, '装配式混凝土建筑施工 第3版', '', 'covers/image318.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (319, '建筑工程测量', '', 'covers/image319.jpg', 9.9, 29, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (320, '建筑工程CAD', '', 'covers/image320.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (321, '装配式混凝土建筑施工 第4版', '', 'covers/image321.jpg', 9.9, 0, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (322, '建筑材料', '', 'covers/image322.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (323, '装配式混凝土建筑施工 第2版', '', 'covers/image323.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (324, '建筑力学与结构 第3版', '', 'covers/image324.jpg', 9.9, 58, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (325, '建设工程监理', '', 'covers/image325.jpg', 9.9, 21, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (326, '土力学与地基基础', '', 'covers/image326.jpg', 9.9, 13, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (327, '建筑材料 第3版', '', 'covers/image327.jpg', 9.9, 50, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (328, '建筑材料 第3版', '', 'covers/image328.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (329, '钢结构制作与安装 第4版', '', 'covers/image329.jpg', 9.9, 25, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (330, '土力学与地基基础第4版', '', 'covers/image330.jpg', 9.9, 28, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (331, '钢筋平法识图与算量(基于22G101图集)', '', 'covers/image331.jpg', 9.9, 21, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (332, '建筑力学与结构 第三版', '', 'covers/image332.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (333, '钢结构工程施工 第四版', '', 'covers/image333.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (334, '建筑施工技术（附施工图）', '', 'covers/image334.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (335, '建筑施工技术 第三版', '', 'covers/image335.jpg', 9.9, 33, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (336, '建筑装饰装修工程施工 第二版', '', 'covers/image336.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (337, '钢结构工程施工第四版', '', 'covers/image337.jpg', 9.9, 27, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (338, 'UG NX 12.0零基础编程实例教程 第2版', '', 'covers/image338.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (339, '建筑施工组织与管理', '', 'covers/image339.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (340, '建筑材料', '', 'covers/image340.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (341, 'UG NX 12.0中文版从入门到精通', '', 'covers/image341.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (342, '建设工程法规', '', 'covers/image342.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (343, '建设工程招标投标与合同管理', '', 'covers/image343.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (344, '建筑工程经济 第二版', '', 'covers/image344.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (345, 'UG NX12.0全实例教程', '', 'covers/image345.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (346, '建筑施工组织与管理 第二版', '', 'covers/image346.jpg', 9.9, 22, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (347, 'UG NX12.0三维建模及自动编程项目教程', '', 'covers/image347.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (348, 'UG NX12.0注塑模具设计实例教程', '', 'covers/image348.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (349, 'UG NX 10.0案例教程', '', 'covers/image349.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (350, '计算机辅助设计——UG NX', '', 'covers/image350.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (351, 'UG NX数控编程学习教程(UG NX12.0)', '', 'covers/image351.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (352, 'UG NX数控编程', '', 'covers/image352.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (353, '机械产品零部件三维建模实用教程(UG NX 12.0版)', '', 'covers/image353.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (354, '气压与液压传动控制技术（第6版）', '', 'covers/image354.jpg', 9.9, 58, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (355, '建筑设备', '', 'covers/image355.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (356, '建筑施工技术', '', 'covers/image356.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (357, '建筑与装饰工程预算', '', 'covers/image357.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (358, '装配式混凝土建筑施工技术', '', 'covers/image358.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (359, '建设工程法规', '', 'covers/image359.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (360, '建筑法规概论第六版', '', 'covers/image360.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (361, '建筑法规概论第五版', '', 'covers/image361.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (362, '建筑法规概论第七版', '', 'covers/image362.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (363, '建筑工程测量第四版', '', 'covers/image363.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (364, '电气设计与制图', '', 'covers/image364.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (365, '电工实训教程第二版', '', 'covers/image365.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (366, '模具设计基础第3版', '', 'covers/image366.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (367, '电机与电气控制技术项目式教程', '', 'covers/image367.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (368, '人工智能基础应用教程', '', 'covers/image368.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (369, '无机及分析化学', '', 'covers/image369.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (370, 'PLC应用与实践三菱', '', 'covers/image370.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (371, '人工智能导论', '', 'covers/image371.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (372, 'Java基础案例教程', '', 'covers/image372.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (373, 'Excel数据分析基础与实践', '', 'covers/image373.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (374, 'Spring Cloud微服务项目开发教程', '', 'covers/image374.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (375, 'Excel数据处理与可视化第二版', '', 'covers/image375.jpg', 9.9, 0, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (376, 'Linux操作系统使用教程第2版', '', 'covers/image376.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (377, '机械设计学习指导', '', 'covers/image377.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (378, '人工智能应用导论第二版', '', 'covers/image378.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (379, '嵌入式应用程序设计综合教程微课版', '', 'covers/image379.jpg', 9.9, 25, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (380, '嵌入式操作系统Linux篇微课版', '', 'covers/image380.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (381, '汽车电气系统检修', '', 'covers/image381.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (382, '智能网联汽车概论', '', 'covers/image382.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (383, '电动汽车结构原理维修', '', 'covers/image383.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (384, '新能源汽车原理与检修', '', 'covers/image384.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (385, '汽车专业英语', '', 'covers/image385.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (386, '汽车顾问式销售', '', 'covers/image386.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (387, '汽车电气系统构造与维修第2版', '', 'covers/image387.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (388, '新能源汽车维护与与故障诊断', '', 'covers/image388.jpg', 9.9, 20, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (389, '电机拖动与调速技术第2版', '', 'covers/image389.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (390, '汽车维修中级工考证训练', '', 'covers/image390.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (391, '液压与气动技术第六版', '', 'covers/image391.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (392, '机械工程基础第5版', '', 'covers/image392.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (393, '汽车维修企业管理第4版', '', 'covers/image393.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (394, '汽车发动机构造与维修第2版', '', 'covers/image394.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (395, '汽车营销实务', '', 'covers/image395.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (396, '新能源汽车专业英语', '', 'covers/image396.jpg', 9.9, 10, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (397, '机械设计基础', '', 'covers/image397.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (398, '人工智能应用概论', '', 'covers/image398.jpg', 9.9, 23, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (399, '汽车商务礼仪第2版', '', 'covers/image399.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (400, '电子技术基础模拟部分第六版', '', 'covers/image400.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (401, '电工技能实训', '', 'covers/image401.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (402, '电梯控制技术第2版', '', 'covers/image402.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (403, '可编程控制器技术第三版', '', 'covers/image403.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (404, '工业控制网络技术第2版', '', 'covers/image404.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (405, '金工实训第四版', '', 'covers/image405.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (406, '建筑结构第三版', '', 'covers/image406.jpg', 9.9, 0, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (407, '传感器应用技术', '', 'covers/image407.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (408, '建筑消防工程第2版', '', 'covers/image408.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (409, '室内装饰工程制图与识图', '', 'covers/image409.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (410, '建筑工程计量与计价第2版', '', 'covers/image410.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (411, 'Unity3D开发标准教程第2版', '', 'covers/image411.jpg', 9.9, 20, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (412, '建筑工程计量与计价实战教程', '', 'covers/image412.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (413, '工程招投标与合同管理', '', 'covers/image413.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (414, '建筑消防工程第三版', '', 'covers/image414.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (415, 'Photoshop图形图像处理技术第二版', '', 'covers/image415.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (416, '安装工程计量与计价', '', 'covers/image416.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (417, '模拟电子技术', '', 'covers/image417.jpg', 9.9, 19, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (418, '金属工艺学 第3版', '', 'covers/image418.jpg', 9.9, 32, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (419, '电子技术基础 模拟部分 第7版', '', 'covers/image419.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (420, '电子技术基础 数字部分 第7版', '', 'covers/image420.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (421, 'SOLIDWORKS工业机器人数字化建模教程', '', 'covers/image421.jpg', 9.9, 34, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (422, '电子技术基础 数字部分 第7版 学习辅导与习题解答', '', 'covers/image422.jpg', 9.9, 16, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (423, 'MySQL数据库基础实例教程 第2版 微课版', '', 'covers/image423.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (424, 'MySQL数据库原理及应用 微课版 第4版', '', 'covers/image424.jpg', 9.9, 14, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (425, '三菱FX系列PLC原理及应用（含仿真与实训）', '', 'covers/image425.jpg', 9.9, 27, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (426, 'MySQL数据库基础实例教程 第3版 微课版', '', 'covers/image426.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (427, 'MySQL数据库原理及应用 微课版 第3版', '', 'covers/image427.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (428, '特种加工技术 第2版', '', 'covers/image428.jpg', 9.9, 35, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (429, '特种加工技术', '', 'covers/image429.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (430, '机械产品三维模型设计（中级）', '', 'covers/image430.jpg', 9.9, 17, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (431, '中文版AutoCAD 2020实用教程 微课视频版', '', 'covers/image431.jpg', 9.9, 19, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (432, '中文版AutoCAD实用教程 案例视频版 2024版', '', 'covers/image432.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (433, 'AutoCAD 2020计算机绘图', '', 'covers/image433.jpg', 9.9, 34, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (434, 'AutoCAD 2016机械设计教程 第2版', '', 'covers/image434.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (435, '计算机辅助电路设计与Altium Designer 17 第3版', '', 'covers/image435.jpg', 9.9, 23, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (436, 'IT项目管理 第2版', '', 'covers/image436.jpg', 9.9, 21, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (437, 'Android应用开发案例教程 Android Studio版', '', 'covers/image437.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (438, 'Android Studio移动应用开发任务教程 微课版', '', 'covers/image438.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (439, 'Android移动应用开发基础教程 微课版', '', 'covers/image439.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (440, 'Android移动开发基础案例教程 第2版', '', 'covers/image440.jpg', 9.9, 17, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (441, 'Android应用开发案例教程 Android Studio版 第2版 微课版', '', 'covers/image441.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (442, '新编高等数学第2版', '', 'covers/image442.jpg', 9.9, 17, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (443, 'Visual C#程序设计与软件项目实训 第2版', '', 'covers/image443.jpg', 9.9, 24, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (444, '高等数学', '', 'covers/image444.jpg', 9.9, 20, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (445, 'C语言程序设计项目化教程 含实训指导 下', '', 'covers/image445.jpg', 9.9, 39, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (446, '应用高等数学', '', 'covers/image446.jpg', 9.9, 38, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (447, '零部件测绘实训指导 第三版', '', 'covers/image447.jpg', 9.9, 67, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (448, '互换性与测量技术基础3D版', '', 'covers/image448.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (449, '机械原理3D版', '', 'covers/image449.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (450, '机械制造基础3D版', '', 'covers/image450.jpg', 9.9, 46, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (451, '电机与电气控制技术项目式教程 第2版', '', 'covers/image451.jpg', 9.9, 9, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (452, 'C++程序设计题解与上机指导 第3版', '', 'covers/image452.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (453, 'C++程序设计 第3版', '', 'covers/image453.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (454, '工业机器人离线编程与仿真', '', 'covers/image454.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (455, '自动控制原理与系统 第5版', '', 'covers/image455.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (456, 'HTML5+CSS3网站设计基础教程 第3版', '', 'covers/image456.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (457, '机械制造工艺与机床夹具 第4版', '', 'covers/image457.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (458, '机械制造工艺与机床夹具 第3版', '', 'covers/image458.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (459, 'Python程序设计项目化教程 微课版', '', 'covers/image459.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (460, '电子电路分析与调试', '', 'covers/image460.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (461, '计算机系统结构2012年版', '', 'covers/image461.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (462, '组态控制技术实训教程（KingView）', '', 'covers/image462.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (463, 'C程序设计(第四版)学习辅导', '', 'covers/image463.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (464, 'Linux网络操作系统实用教程（CentOS 8）（第2版）', '', 'covers/image464.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (465, 'C程序设计（第五版）', '', 'covers/image465.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (466, 'C程序设计（第五版）学习辅导', '', 'covers/image466.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (467, '工业机器人虚拟仿真实用教程（配视频）', '', 'covers/image467.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (468, '气压与液压传动控制技术（第6版）', '', 'covers/image468.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (469, '汽车发动机电控系统检测与维修工作页', '', 'covers/image469.jpg', 9.9, 13, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (470, '智能网联汽车底盘线控技术', '', 'covers/image470.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (471, '新能源汽车电气系统检修', '', 'covers/image471.jpg', 9.9, 11, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (472, '汽车发动机电控系统检修', '', 'covers/image472.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (473, '汽车发动机电控技术第4版', '', 'covers/image473.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (474, '汽车发动机电控系统检修', '', 'covers/image474.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (475, '电子电路分析与调试', '', 'covers/image475.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (476, '工业机器人离线编程与仿真', '', 'covers/image476.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (477, '机械系统设计 第2版', '', 'covers/image477.jpg', 9.9, 20, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (478, '新能源汽车概论 第2版', '', 'covers/image478.jpg', 9.9, 15, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (479, '汽车售后服务实务', '', 'covers/image479.jpg', 9.9, 25, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (480, 'SolidWorks机械产品数字化设计', '', 'covers/image480.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (481, '电力电子技术 第3版 微课版', '', 'covers/image481.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (482, '钳工实习', '', 'covers/image482.jpg', 9.9, 19, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (483, '大学物理 第3版', '', 'covers/image483.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (484, '金工实训 第四版', '', 'covers/image484.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (485, '机械设计基础 第5版', '', 'covers/image485.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (486, '数控机床结构与维护 第2版', '', 'covers/image486.jpg', 9.9, 4, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (487, '射频识别(RFID)应用技术 第3版（微课版）', '', 'covers/image487.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (488, '机械工程基础', '', 'covers/image488.jpg', 9.9, 8, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (489, '建筑工程施工工艺 第三版', '', 'covers/image489.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (490, '行知行业英语 电子工业', '', 'covers/image490.jpg', 9.9, 17, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (491, '建筑构造', '', 'covers/image491.jpg', 9.9, 3, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (492, '数字孪生——产线工艺仿真', '', 'covers/image492.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (493, '环境工程原理 第三版', '', 'covers/image493.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (494, '金属工艺学 第3版', '', 'covers/image494.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (495, '建筑法规', '', 'covers/image495.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (496, '数字孪生——机电概念设计与仿真', '', 'covers/image496.jpg', 9.9, 17, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (497, '建筑法规概论', '', 'covers/image497.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (498, '传感器与智能检测技术 微课视频版', '', 'covers/image498.jpg', 9.9, 44, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (499, '模拟电子技术 第6版', '', 'covers/image499.jpg', 9.9, 22, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (500, '汽车发动机电控系统检修', '', 'covers/image500.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (501, 'Python数据分析与应用 第3版 微课版', '', 'covers/image501.jpg', 9.9, 0, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (502, 'Python编程基础 第2版 微课版', '', 'covers/image502.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (503, 'Python程序设计项目教程——从入门到实践 微课版', '', 'covers/image503.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (504, '多轴数控编程与加工案例教程 第2版', '', 'covers/image504.jpg', 9.9, 37, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (505, 'Python编程基础 第3版 微课版', '', 'covers/image505.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (506, 'Python数据分析与应用 第2版 微课版', '', 'covers/image506.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (507, 'SolidWorks 2022基础与实例教程', '', 'covers/image507.jpg', 9.9, 20, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (508, '公差配合与技术测量 第2版', '', 'covers/image508.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (509, 'C51单片机应用技术项目教程', '', 'covers/image509.jpg', 9.9, 34, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (510, 'Linux操作系统管理及应用', '', 'covers/image510.jpg', 9.9, 27, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (511, '设计基础第5版', '', 'covers/image511.jpg', 9.9, 23, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (512, '机械制图与CAD习题集', '', 'covers/image512.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (513, '机械制图与CAD', '', 'covers/image513.jpg', 9.9, 12, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (514, 'AutoCAD机械制图', '', 'covers/image514.jpg', 9.9, 27, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (515, 'AutoCAD机械绘图', '', 'covers/image515.jpg', 9.9, 35, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (516, '建筑工程计量与计价实战教程', '', 'covers/image516.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (517, '机械制图与CAD', '', 'covers/image517.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (518, 'AutoCAD 2016机械制图实例教程', '', 'covers/image518.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (519, 'AutoCAD 2016绘图教程', '', 'covers/image519.jpg', 9.9, 6, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (520, 'AutoCAD 2018机械产品辅助设计案例教程', '', 'covers/image520.jpg', 9.9, 1, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (521, 'AutoCAD 2018项目教程', '', 'covers/image521.jpg', 9.9, 29, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (522, '计算机网络技术基础（第2版）', '', 'covers/image522.jpg', 9.9, 32, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (523, 'C语言程序设计案例式教程 第2版', '', 'covers/image523.jpg', 9.9, 34, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (524, 'Java语言程序设计与实现 微课版 第2版', '', 'covers/image524.jpg', 9.9, 24, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (525, 'Java基础案例教程 第2版', '', 'covers/image525.jpg', 9.9, 2, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (526, 'Java程序设计', '', 'covers/image526.jpg', 9.9, 19, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (527, 'C语言程序设计基础教程', '', 'covers/image527.jpg', 9.9, 28, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (528, '高等数学第四版', '', 'covers/image528.jpg', 9.9, 22, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (529, '高等数学 第八版 上册', '', 'covers/image529.jpg', 9.9, 5, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (530, '高等数学 第八版 下册', '', 'covers/image530.jpg', 9.9, 7, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (531, '高等数学 第七版 下册', '', 'covers/image531.jpg', 9.9, 15, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (532, '传感器技术与应用 第2版', '', 'covers/image532.jpg', 9.9, 34, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (533, '高职院校思想政治理论课实践教程（已刮码）', '', 'covers/image533.jpg', 9.9, 50, '');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (534, '大学生心理健康教育', '', 'covers/image534.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (535, '大学军事理论教程', '', 'covers/image535.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (536, '通用英语1', '', 'covers/image536.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (537, '大学生就业指导实务', '', 'covers/image537.jpeg', 16.66, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (538, '创新思维与创业管理(第2版)', '', 'covers/image538.jpeg', 9.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (539, '国家安全教育大学生读本', '', 'covers/image539.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (540, '高职体育立体化教程(微课版)', '', 'covers/image540.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (541, '中国共产党简史', '', 'covers/image541.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (542, '通用英语2', '', 'covers/image542.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (543, '信息技术基础(微课版)', '', 'covers/image543.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (544, '思想道德与法治 (2023年版）', '', 'covers/image544.jpeg', 6.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (545, '梦想起航大学生职业生涯规划', '', 'covers/image545.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (546, '毛泽东思想和中国特色社会主义理论体系2023年版', '', 'covers/image546.jpeg', 6.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (547, '习近平新时代中国特色社会主义思想概论', '', 'covers/image547.jpeg', 6.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (548, '创新思维与创业管理', '', 'covers/image548.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (549, '大学生就业指导实务', '', 'covers/image549.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (550, '大学生生涯发展与就业力提升', '', 'covers/image550.jpeg', 8.8, 20, '公共课');
INSERT INTO books (id, title, author, cover, price, stock, category) VALUES (551, '时事报告', '', 'covers/image551.png', 8.8, 20, '公共课');
